[module/wwan]
type = internal/network
interface = wwp0s20f0u3c2
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %local_ip%

format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground}

ramp-signal-0 = 1
ramp-signal-1 = 2
ramp-signal-2 = 3
ramp-signal-3 = 4
ramp-signal-4 = 5
ramp-signal-foreground = ${colors.foreground}